name: Telegram Bot Runner

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run bot forever loop
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          while true
          do
            python bot.py
            echo restarting...
            sleep 3
          done
